apiVersion: apps/v1
kind: Deployment
metadata:
  name: order2
  labels:
    app: order2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order2
  template:
    metadata:
      labels:
        app: order2
    spec:
      containers:
        - name: order2
          image: username/order2:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5